apiVersion : apps/v1
kind : Deployment
metadata :
  name : init-container-service
  labels :
    app : init-container-service
spec :
  replicas : 1
  strategy :
    type : RollingUpdate
  selector :
    matchLabels :
      app : init-container-service
  template :
    metadata :
      labels :
        app : init-container-service
    spec :
      containers :
        - name : init-container-service
          image : docker-registry.ujar.org/ujar/micro-k8s-bookingdb-init-container-service:latest
          imagePullPolicy: Always
          ports :
            - containerPort : 8080
          env :
            - name : DATASOURCE_URL
              valueFrom :
                configMapKeyRef :
                  name : init-container-service
                  key : datasource-url
            - name : DATASOURCE_USERNAME
              valueFrom :
                secretKeyRef :
                  name : init-container-service
                  key : datasource-username
            - name : DATASOURCE_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : init-container-service
                  key : datasource-password
          resources :
            requests :
              cpu : "0.2"
              memory : 300Mi
            limits :
              cpu : "1.0"
              memory : 300Mi
          readinessProbe :
            httpGet :
              port : 8080
              path: /actuator/health/readiness
            initialDelaySeconds : 50
            timeoutSeconds : 2
            periodSeconds : 20
            failureThreshold : 5
          livenessProbe :
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds : 50
            timeoutSeconds : 2
            periodSeconds : 20
            failureThreshold : 5
          startupProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 5
      serviceAccountName : api-service-account
---
apiVersion : v1
kind : Service
metadata :
  name : init-container-service
  labels :
    app : init-container-service
spec :
  ports :
    - port : 8080
      targetPort : 8080
      protocol : TCP
  selector :
    app : init-container-service
