apiVersion : apps/v1
kind : Deployment
metadata :
  name : mysql
  labels :
    app : mysql
spec :
  replicas : 1
  selector :
    matchLabels :
      app : mysql
  template :
    metadata :
      labels :
        app : mysql
    spec :
      containers :
        - name : mysql
          image : mysql:5.7.34
          ports :
            - containerPort : 3306
          env :
            - name : MYSQL_DATABASE
              valueFrom :
                configMapKeyRef :
                  name : mysql
                  key : database-name
            - name : MYSQL_USER
              valueFrom :
                secretKeyRef :
                  name : mysql
                  key : database-user
            - name : MYSQL_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : mysql
                  key : database-password
            - name : MYSQL_ROOT_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : mysql
                  key : database-root-password
          resources :
            requests :
              cpu : "0.2"
              memory : 300Mi
            limits :
              cpu : "1.0"
              memory : 300Mi
          readinessProbe :
            tcpSocket :
              port : 3306
            initialDelaySeconds : 50
            timeoutSeconds : 2
            periodSeconds : 20
            failureThreshold : 5
          livenessProbe :
            tcpSocket :
              port : 3306
            initialDelaySeconds : 50
            timeoutSeconds : 2
            periodSeconds : 20
            failureThreshold : 5
      serviceAccountName : api-service-account
---
apiVersion : v1
kind : Service
metadata :
  name : mysql
  labels :
    app : mysql
spec :
  ports :
    - port : 3306
      protocol : TCP
  selector :
    app : mysql
