apiVersion : v1
kind : ConfigMap
metadata :
  name : importer-service
data :
  swagger-ui-relative-path : "/importer/"
  logging-level-root: TRACE
  datasource-url : jdbc:mysql://mysql:3306/sa_test_db
  rabbitmq-host : rabbitmq
  rabbitmq-port : "5672"
